name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login ke Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_ACCESSTOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 3. Build Docker Image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/uas-pcc-beryl-2025:latest -f Dockerfile .

      # 4. Push Docker Image ke Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/uas-pcc-beryl-2025:latest